// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.2.0.0
//      SpecFlow Generator Version:2.2.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace TodoMVC.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.2.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [TechTalk.SpecRun.FeatureAttribute("TodoMVC AngularJS", SourceFile="Features\\TodoMVC.feature", SourceLine=0)]
    public partial class TodoMVCAngularJSFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "TodoMVC.feature"
#line hidden
        
        [TechTalk.SpecRun.FeatureInitialize()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "TodoMVC AngularJS", null, ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [TechTalk.SpecRun.FeatureCleanup()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        [TechTalk.SpecRun.ScenarioCleanup()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Add items to list", new string[] {
                "AddNewItems"}, SourceLine=3)]
        public virtual void AddItemsToList()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Add items to list", new string[] {
                        "AddNewItems"});
#line 4
this.ScenarioSetup(scenarioInfo);
#line 5
testRunner.Given("I am on todomvc website", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "todoitems"});
            table1.AddRow(new string[] {
                        "Automation"});
            table1.AddRow(new string[] {
                        "BDD Scenarios"});
            table1.AddRow(new string[] {
                        "Learn C#"});
#line 6
testRunner.When("I add items to the list", ((string)(null)), table1, "When ");
#line 11
testRunner.Then("I see checkbox in front of every todo item in the list", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 12
testRunner.And("I see number of items left, All button, Active button, Completed button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 13
testRunner.And("the number of items left count should match the number of Active items", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 14
testRunner.And("I see All button in selected state", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Mark an Item as completed", new string[] {
                "MarkItemAsCompleted"}, SourceLine=16)]
        public virtual void MarkAnItemAsCompleted()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Mark an Item as completed", new string[] {
                        "MarkItemAsCompleted"});
#line 17
this.ScenarioSetup(scenarioInfo);
#line 18
testRunner.Given("I am on todomvc website", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "todoitems"});
            table2.AddRow(new string[] {
                        "Automation"});
            table2.AddRow(new string[] {
                        "BDD Scenarios"});
            table2.AddRow(new string[] {
                        "Learn C#"});
#line 19
testRunner.When("I add items to the list", ((string)(null)), table2, "When ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Completeditem"});
            table3.AddRow(new string[] {
                        "BDD Scenarios"});
#line 24
testRunner.And("I click on checkbox of completed item", ((string)(null)), table3, "And ");
#line 27
testRunner.Then("I see the completed item striked out", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 28
testRunner.And("I see the checkbox ticked in green for completed item", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 29
testRunner.And("I see number of items left, All button, Active button, Completed button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 30
testRunner.And("I see clear completed button populated", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 31
testRunner.And("the number of items left count should match the number of Active items", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 32
testRunner.And("I see Completed button in selected state", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Display All todo items from the list", new string[] {
                "DisplayAllItems"}, SourceLine=34)]
        public virtual void DisplayAllTodoItemsFromTheList()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Display All todo items from the list", new string[] {
                        "DisplayAllItems"});
#line 35
this.ScenarioSetup(scenarioInfo);
#line 36
testRunner.Given("I am on todomvc website", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "todoitems"});
            table4.AddRow(new string[] {
                        "Automation"});
            table4.AddRow(new string[] {
                        "BDD Scenarios"});
            table4.AddRow(new string[] {
                        "Learn C#"});
#line 37
testRunner.When("I add items to the list", ((string)(null)), table4, "When ");
#line 42
testRunner.And("I click on All button to see both completed and Active items", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 43
testRunner.Then("I see All items from the list", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 44
testRunner.And("I see checkbox in front of every todo item in the list", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 45
testRunner.And("I see number of items left, All button, Active button, Completed button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 46
testRunner.And("the number of items left count should match the number of Active items", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 47
testRunner.And("I see All button in selected state", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Display Active todo items from the list", new string[] {
                "DisplayActiveItems"}, SourceLine=50)]
        public virtual void DisplayActiveTodoItemsFromTheList()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Display Active todo items from the list", new string[] {
                        "DisplayActiveItems"});
#line 51
this.ScenarioSetup(scenarioInfo);
#line 52
testRunner.Given("I am on todomvc website", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "todoitems"});
            table5.AddRow(new string[] {
                        "Automation"});
            table5.AddRow(new string[] {
                        "BDD Scenarios"});
            table5.AddRow(new string[] {
                        "Learn C#"});
#line 53
testRunner.When("I add items to the list", ((string)(null)), table5, "When ");
#line 58
testRunner.And("I click on Active button to see all active items", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 59
testRunner.Then("I see only Active items from the list", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 60
testRunner.And("I see checkbox in front of every todo item in the list", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 61
testRunner.And("I see number of items left, All button, Active button, Completed button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 62
testRunner.And("the number of items left count should match the number of Active items", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 63
testRunner.And("I see Active button in selected state", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 64
testRunner.When("I click on Active item checkbox", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 65
testRunner.Then("the item disappears from the list", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Mark and display completed todo items from the list", new string[] {
                "DisplayCompletedItems"}, SourceLine=68)]
        public virtual void MarkAndDisplayCompletedTodoItemsFromTheList()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Mark and display completed todo items from the list", new string[] {
                        "DisplayCompletedItems"});
#line 69
this.ScenarioSetup(scenarioInfo);
#line 70
testRunner.Given("I am on todomvc website", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "todoitems"});
            table6.AddRow(new string[] {
                        "Automation"});
            table6.AddRow(new string[] {
                        "BDD Scenarios"});
            table6.AddRow(new string[] {
                        "Learn C#"});
#line 71
testRunner.When("I add items to the list", ((string)(null)), table6, "When ");
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "Completeditem"});
            table7.AddRow(new string[] {
                        "BDD Scenarios"});
#line 76
testRunner.And("I click on checkbox of completed item", ((string)(null)), table7, "And ");
#line 79
testRunner.And("I click on Completed button to see all completed items", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 80
testRunner.Then("I see only completed items from the list", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 81
testRunner.Then("I see the completed item striked out", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 82
testRunner.And("I see the checkbox ticked in green for completed item", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 83
testRunner.And("I see number of items left, All button, Active button, Completed button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 84
testRunner.And("I see clear completed button populated", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 85
testRunner.And("the number of items left count should match the number of Active items", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 86
testRunner.And("I see Completed button in selected state", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 87
testRunner.When("I click on completed item checkbox", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 88
testRunner.Then("the item disappears from the list", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Clear completed todo items from the list", new string[] {
                "ClearCompletedItems"}, SourceLine=91)]
        public virtual void ClearCompletedTodoItemsFromTheList()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Clear completed todo items from the list", new string[] {
                        "ClearCompletedItems"});
#line 92
this.ScenarioSetup(scenarioInfo);
#line 93
testRunner.Given("I am on todomvc website", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                        "todoitems"});
            table8.AddRow(new string[] {
                        "Automation"});
            table8.AddRow(new string[] {
                        "BDD Scenarios"});
            table8.AddRow(new string[] {
                        "Learn C#"});
#line 94
testRunner.When("I add items to the list", ((string)(null)), table8, "When ");
#line hidden
            TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                        "Completeditem"});
            table9.AddRow(new string[] {
                        "BDD Scenarios"});
#line 99
testRunner.And("I click on checkbox of completed item", ((string)(null)), table9, "And ");
#line 102
testRunner.Then("I see clear completed button populated", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 103
testRunner.When("I click on Clear completed button populated", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 104
testRunner.Then("I see completed items checkbox unticked", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 105
testRunner.And("I see number of items left, All button, Active button, Completed button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 106
testRunner.And("the number of items left count should match the number of Active items", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 107
testRunner.And("I do not see clear completed button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 108
testRunner.And("I see All button in selected state", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Edit a todo item from the list", new string[] {
                "EditTodoItem"}, SourceLine=111)]
        public virtual void EditATodoItemFromTheList()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Edit a todo item from the list", new string[] {
                        "EditTodoItem"});
#line 112
this.ScenarioSetup(scenarioInfo);
#line 113
testRunner.Given("I am on todomvc website", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                        "todoitems"});
            table10.AddRow(new string[] {
                        "Automation"});
            table10.AddRow(new string[] {
                        "BDD Scenarios"});
            table10.AddRow(new string[] {
                        "Learn C#"});
#line 114
testRunner.When("I add items to the list", ((string)(null)), table10, "When ");
#line 119
testRunner.And("I double click on a todo item from the list", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 120
testRunner.Then("I can edit a todo item", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 121
testRunner.And("I see number of items left, All button, Active button, Completed button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 122
testRunner.And("the number of items left count should match the number of Active items", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Remove a todo item from the list", new string[] {
                "RemoveTodoItem"}, SourceLine=125)]
        public virtual void RemoveATodoItemFromTheList()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Remove a todo item from the list", new string[] {
                        "RemoveTodoItem"});
#line 126
this.ScenarioSetup(scenarioInfo);
#line 127
testRunner.Given("I am on todomvc website", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table11 = new TechTalk.SpecFlow.Table(new string[] {
                        "todoitems"});
            table11.AddRow(new string[] {
                        "Automation"});
            table11.AddRow(new string[] {
                        "BDD Scenarios"});
            table11.AddRow(new string[] {
                        "Learn C#"});
#line 128
testRunner.When("I add items to the list", ((string)(null)), table11, "When ");
#line 133
testRunner.And("I see New item added to the list", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 134
testRunner.And("I tick completed items in the checkbox", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 135
testRunner.And("I click on \"x\" next to todo item", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 136
testRunner.Then("I see the todo item removed from the list", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 137
testRunner.And("I see number of items left, All button, Active button, Completed button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 138
testRunner.And("the number of items left count should match the number of Active items", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.TestRunCleanup()]
        public virtual void TestRunCleanup()
        {
            TechTalk.SpecFlow.TestRunnerManager.GetTestRunner().OnTestRunEnd();
        }
    }
}
#pragma warning restore
#endregion
